### PR TITLE
Tabs redo

### PR DESCRIPTION
**Pull request by dgrammatiko**
## Fixing what's broken

- Rewritten so there are no more moving elements in the DOM
- Added `breakpoint` attribute to control the transition from tabs to accordion and vice versa
- Tab elements are moved from `section` to `joomla-tab-element` (mildly B/C break)
- ~~Tabs container element renamed from `joomla-tab` to `joomla-tabs` (mildly B/C break)~~ nope

A11y based on 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/accordion/accordion.html
and 
https://www.w3.org/TR/wai-aria-practices-1.1/examples/tabs/tabs-1/tabs.html

Docs, preview:
Screenshot 2021-07-17 at 14 37 44

### CODE REVIEW

**Comment by richard67** [comment]
@dgrammatiko Is the "WIP" at the top of the description still true?

**Comment by dgrammatiko** [comment]
@richard67 There's one change pending (I got something wrong), will update it shortly

**Comment by richard67** [comment]
@wilsonge As the CMS PR #34813 using the last commit here has received 2 successful tests, can we get this one here merged and a new tag or release being made, so PR #34813 can be updated to use that?

**Comment by dgrammatiko** [comment]
@wilsonge if you're ok with this please make a patch release (0.2.0) to keep things whithin SEMVER

**Comment by Bakual** [comment]
Actually, it should become 1.0.0 since we're going to use it in production. 0.x.x releases are not meant to be used in production.

See https://semver.org/#spec-item-4

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

**Comment by wilsonge** [comment]
I’m not at home right now so will do the release later. But Thankyou!

**Comment by dgrammatiko** [comment]
I need to fix the saucelabs tests to fire without the label attach procedure.

Thanks

**Comment by wilsonge** [comment]
Released

**Comment by bembelimen** [comment]
Sorry to be late for the party: thanks for the rebuild @dgrammatiko the tabs are very cool.

**Pull request merged**
