### PR TITLE
Allow to toggle accordion on click

### PR DESCRIPTION
**Pull request by Fedik**
This allow to toggle accordion on click.

fix for 
https://github.com/joomla/joomla-cms/issues/29580  
https://github.com/joomla/joomla-cms/issues/29580#issuecomment-643653990

### CODE REVIEW

**Comment by infograf768** [comment]
This works great!

tabs_accordeon

@HLeithner @wilsonge 

Please merge.

**Comment by HLeithner** [comment]
Thanks

**Comment by infograf768** [comment]
Thanks, how do we get this in core?

**Comment by Fedik** [comment]
I think someone should tag new release here, then in Joomla `npm update joomla-ui-custom-elements` (or update all :))

**Pull request merged**
