### PR TITLE
Fix docs

### PR DESCRIPTION
**Pull request by C-Lodder**
### Changes

- Fix the docs
- Asynchronously loads CSS/JS files
- Fix the links going to BS, UIKit and Foundation pages
- Update `ce-loader.js` which removes the `console.warn` as mentioned here https://github.com/joomla/joomla-cms/issues/17914

### CODE REVIEW

**Comment by C-Lodder** [comment]
@brianteeman @wilsonge suppose it's up to you guys to review now :)

**Comment by mbabker** [comment]
Someone care explaining what all the Travis failures mean?  #OverMyHead

**Comment by C-Lodder** [comment]
@mbabker I can fix those in this PR or a separate one. Up to you

**Comment by mbabker** [comment]
#YOLO

Seems to be how things merge these days anyway in some parts of the project

**Pull request merged**
