### PR TITLE
[Tab] Fix activating tabs by URL hash

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for https://github.com/joomla/joomla-cms/issues/27845.

Note, nested tabs are still totally broken.

### CODE REVIEW

**Comment by Quy** [comment]
Tested successfully! Thanks.

**Comment by wilsonge** [comment]
When you say nested tabs are still broken - what exactly is broken? I definitely fixed SOME of nested tabs at some point (although not all)

**Comment by SharkyKZ** [comment]
Activating nested tabs by URL. I had that working but kept getting errors in console. I'll look into this later.

**Comment by wilsonge** [comment]
gotcha. ta

**Pull request merged**
