### PR TITLE
[DRAFT] move to individual scss

### PR DESCRIPTION
**Pull request by N6REJ**
Don't understand how to compile these into the css though.  Tried running build but it failed.
image

### CODE REVIEW

**Comment by C-Lodder** [comment]
In your terminal, just run `grunt compile`.

**Comment by N6REJ** [comment]
@C-Lodder sorry to keep bothering you.  so, apparently I didn't have grunt, so I followed the directions and ran
npm install -g grunt-cli
tried "grunt compile" and it said it couldn't find grunt.
did some research and it said to run
npm install grunt --save-dev
so I ran it with the -g option and that didnt' solve the issue.. then I tried it without the -g and it did then allow grunt compile to run, HOWEVER it came up with more errors...
image

**Comment by N6REJ** [comment]
after running a LOT of npm install .... I finally get it to compile but I get 
Running "postcss:tip" (postcss) task
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.pos
tcss.parts/ and use them in postcss.config.js.
>> File dist/css/joomla-tip.css created. 3.19 kB → 3.19 kB
1 processed stylesheet created. 3.19 kB → 3.19 kB

*sigh*

**Comment by dgrammatiko** [comment]
@N6REJ can I ask what are you trying to achieve here?

These functions **were** part of the actual element as an architectural decision (my decision fwiw), so if you want to revert that you have to explain what are the gains, what problem it solves, etc.

**Comment by C-Lodder** [comment]
@dgrammatiko cause if additional custom elements are added in the future that require these mixins/functions, you can simply import the file, rather than having to copy/paste them.

**Comment by dgrammatiko** [comment]
@C-Lodder the idea was/is to move to lerna and make this a monorepo (eg each component has it's own lifecycle, package,etc). So according to my vision splitting things is not a thing as each component **should** be completely independent...

**Comment by N6REJ** [comment]
@dgrammatiko started with #147

**Pull request closed without merging**
