### PR TITLE
[4.0] Change role attribute value

### PR DESCRIPTION
**Pull request by hardik-codes**
Pull request for issue #22507(joomla-cms)
https://github.com/joomla/joomla-cms/issues/22507

## Summary of Changes
Changed ```role``` attribute value from ```alert``` to ```alertdialog``` as mentioned in the issue

### CODE REVIEW

**Comment by hardik-codes** [comment]
@HLeithner @C-Lodder  please review.

**Comment by C-Lodder** [comment]
@hardik-codes You've committed the minified file so I can't see what changes have been made. Please commit the `src` file too

**Comment by hardik-codes** [comment]
Will do so
One thing more do I have to npm run build:js before committing the src file

**Comment by hardik-codes** [comment]
Now have a look @C-Lodder

**Pull request merged**
