### PR TITLE
Adding RTL override for alerts

### PR DESCRIPTION
**Pull request by infograf768**
@wilsonge
Thanks you for merging and compiling.

### CODE REVIEW

**Comment by infograf768** [comment]
No idea why travis fails. :)

**Comment by C-Lodder** [comment]
This doesn't look correct at all

**Comment by C-Lodder** [comment]
Don't worry about the Travis error for now. It's part of the automated browser tests

**Comment by C-Lodder** [comment]
But please change the code to the following:

```
html[dir="rtl"] joomla-alert {
  .joomla-alert--close,
  .joomla-alert-button--close {
    float: left;
    right: auto;
    left: -1.25rem;
  }
}
```

**Comment by infograf768** [comment]
Should be OK now.

**Comment by infograf768** [comment]
@C-Lodder 
Are you sure it is
`html["dir=rtl"]` and not as I did `html[dir=rtl]`

**Comment by infograf768** [comment]
In fact I am pretty sure there should not be any double quotes.

**Comment by C-Lodder** [comment]
I dont think the quotes matter to be honest

**Pull request merged**
