### PR TITLE
Fix tab issue in Joomla 4

### PR DESCRIPTION
**Pull request by Anu1601CS**
PR for issue https://github.com/joomla/joomla-cms/issues/21855
We are currently getting issue in new `uitab` for joomla 4 . 
Like this 
44949328-86057280-ae2f-11e8-87b8-556d22e571d8

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Sorry this is totally wrong, explanation here: https://codepen.io/dgrammatiko/pen/EeWQWo

**Comment by Anu1601CS** [comment]
Ok @dgrammatiko

**Comment by laoneo** [comment]
So the solution would be to add .length in the if and the pr would be correct then?

**Comment by dgrammatiko** [comment]
@laoneo obviously not. If you do this then you force the script to behave as there is always a nested tab collection which is not how the script should function. The bug is obviously not in this line...

**Pull request closed without merging**
