### PR TITLE
Migrate from Travis CI to Github Actions

### PR DESCRIPTION
**Pull request by wilsonge**

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@wilsonge merge it

**Comment by C-Lodder** [comment]
@wilsonge Can I suggest you have another GH action that run a test build on the LTS *and* current version of Node.JS? Cause right now, it won't you on the current

**Comment by wilsonge** [comment]
I don't think it makes a difference. We aren't running any unit tests right now in the code - only lint (which is the same independent of node version - and the system tests that run through sauce labs). If anything fails on different node versions then it's just going to be our build tools not supporting that version of node as opposed to it being an issue with the package we distribute.

**Comment by C-Lodder** [comment]
Exactly, so how will you know if a specific node version works?
Remember that this is a Joomla agnostic repo so people out there may not even be using it for Joomla. It needs to be able to work on the latest Node.js version, so without running an action, you probably won't find out until it becomes LTS.

**Pull request merged**
