### PR TITLE
Grunt es6, package.json cleaning

### PR DESCRIPTION
**Pull request by dgt41**

### CODE REVIEW

**Comment by dgt41** [comment]
@C-Lodder can you delete your `node_modules` folder and re run `npm i`? Does Grunt work there ok??

**Comment by C-Lodder** [comment]
Normally deprecated noticed get ignored, however the first one I get is:

> npm WARN deprecated grunt-es6-transpiler@1.0.2: Deprecated. Check out [grunt-babel](https://github.com/babel/grunt-babel) instead.

which halts everything

**Comment by C-Lodder** [comment]
I used for `--force` flag which installed all the dependencies (few other notices but nothing major), then ran `grunt`. Compiling worked fine and seemed a little faster too.

**Comment by C-Lodder** [comment]
Everything working fine now. You happy with it?

**Comment by dgt41** [comment]
yup

**Pull request merged**
