### PR TITLE
Minor changes on CSS & README

### PR DESCRIPTION
**Pull request by spahno**
### Summary of Changes
Centered the text from the success-alert when deleting/uploading a media.
(Additionally added a "!" to the README.me).

### Testing Instructions
Install the 4.0-dev

### CODE REVIEW

**Comment by brianteeman** [comment]
a text string should never be center aligned.

**Comment by C-Lodder** [comment]
This is not the correct place to be making the change. The custom elements are supposed to be Joomla agnostic. If the J4 templates require the text to be aligned to the center, then this shhould be done at template level, not here.

**Comment by spahno** [comment]
> a text string should never be center aligned.

Hey @brianteeman,
would you please explain to me why?

**Comment by brianteeman** [comment]
https://uxmovement.com/content/why-you-should-never-center-align-paragraph-text/

**Pull request closed without merging**
